#!/usr/bin/env python3


from testvideo import upload_testvideo
from session import FrikanalenSession


if __name__ == '__main__':
    fk = FrikanalenSession('dev-admin@frikanalen.no', 'dev-admin')
    print(upload_testvideo(fk))
