#!/usr/bin/env python3

from tqdm import tqdm
from tusclient import client
import requests
import os
import time

UPLOAD_CHUNK_SIZE = 1024 * 1024
FK_API = 'http://localhost:8000'
FK_API_KEY = '1234'

SESSION_COOKIE = 'fk:session'
CSRF_COOKIE = 'fk:csrf'


def open_session(email, password):
    session_req = requests.post(
        f'{FK_API}/auth/login',
        {'email': email, 'password': password}
    )

    return (session_req.cookies[SESSION_COOKIE], session_req.cookies[CSRF_COOKIE])


def get_frikanalen_tus_client():
    def _encode_cookies(cookies: dict) -> str:
        return '; '.join(['='.join(cookie) for cookie in cookies.items()])

    tus_cookies = _encode_cookies({
        SESSION_COOKIE: session,
        CSRF_COOKIE: csrf
    })

    tus_headers = {
        'Cookie': tus_cookies,
        'X-CSRF-Token': csrf,
    }

    return client.TusClient(f'{FK_API}/videos/upload/', tus_headers)


def get_frikanalen_tus_uploader(file_path: str):
    file_name = os.path.basename(file_path)
    file_stream = open(file_path, 'rb')
    tus_client = get_frikanalen_tus_client()
    return tus_client.uploader(file_stream=file_stream,
                               chunk_size=UPLOAD_CHUNK_SIZE,
                               metadata={'fileName': file_name})


def upload_file(file_path: str):
    tus_uploader = get_frikanalen_tus_uploader(file_path)
    file_size = os.stat(file_path).st_size
    progress_bar = tqdm(total=file_size, unit_scale=True, unit='B')

    while tus_uploader.offset < file_size:
        tus_uploader.upload_chunk()
        progress_bar.update(UPLOAD_CHUNK_SIZE)

    progress_bar.close()

    upload_id = tus_uploader.url.split('/')[-1]

    while True:
        time.sleep(1)

        new_id_req = requests.get(
            f'{FK_API}/videos/media/tus/{upload_id}',
            headers={'X-API-Key': FK_API_KEY}
        )

        if new_id_req.ok:
            print(new_id_req.json)
            return new_id_req.content

        print(new_id_req)
        print("video not yet registered in system, waiting...")
        time.sleep(5)


if __name__ == '__main__':
    session, csrf = open_session('dev-admin@frikanalen.no', 'dev-admin')
    upload_file('../CLUNKS-_8R64-WZwjw.mp4')
